name: Bug Report
description: Report a problem.
labels: bug

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: If possible, please include code that reproduces the failure.
      placeholder: |
        Steps to reproduce the behavior:
        1. Visit page ...
        2. Click link ...
        3. See error

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: Actual behavior
      description: What you observed instead of the expected behavior?

  - type: textarea
    attributes:
      label: "Additional: Context"
      description: Add any other context about the problem here.
