# theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
locale: "en-US"
title: ROHD
title_separator: "-"
subtitle: "The Rapid Open Hardware Development Framework"
email: "yao.jing.quek@intel.com"
description: "A better way to develop hardware The Rapid Open Hardware Development (ROHD) framework is a framework for describing and verifying hardware in the Dart programming language."
url: "https://intel.github.io/rohd-website" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
repository: "intel/rohd"
logo: "/assets/images/88x88.svg"
# masthead_title: "ROHD"
breadcrumbs: true
minimal_mistakes_skin: "air"
search: true
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)

plugins:
  - jekyll-include-cache

include:
  - _pages

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  get-started:
    output: true
    permalink: /:collection/:path/
  blog:
    output: true
    permalink: /:collection/:path/
  forum:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: get-started
    values:
      layout: single
      sidebar:
        nav: "get-started"
    
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  
  - scope:
      path: ""
      type: blog
    values:
      layout: single
      toc: false
      author_profile: true
      show_date: true
      read_time: true
      sidebar:
        nav: "blog"
  - scope:
      path: ""
      type: forum
    values:
      layout: single
      sidebar:
        nav: "forum"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-1NDPL009FG"
    anonymize_ip: false # default
