name: General
on:
  push:
    branches:
      - rohd-website
  pull_request:
    branches:
      - rohd-website
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-checks:
    name: Run Checks
    permissions: {}
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: '**/*.md #rohd/api/static-assets/readme.md'

      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes # output is too noisy, see https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/121
          config-file: .github/configs/mlc_config.json
    
  deploy-website:
    timeout-minutes: 30
    permissions: {}
    runs-on: ubuntu-22.04
    steps:
      - name: Sync ROHD docs
        run: tool/gh_actions/update_directory.sh



        

