name: General
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Top-level default, no permissions
permissions: {}

jobs:
  run-checks:
    name: Run Checks
    permissions: {}
    timeout-minutes: 30
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md #rohd/api/static-assets/readme.md'

      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes # output is too noisy, see https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/121
          config-file: .github/configs/mlc_config.json
      
      - uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v3
        with:
          gemfile-location: '/docs'
          site-directory: '/docs'
