name: update website
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '5 8 * * 0' # Evry Sunday 8.05
  workflow_dispatch:

jobs:
  update_submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: deploy-website

      - name: Merge main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: deploy-website
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd
        
      - name: update src content
        run: tool/gh_actions/update_directory.sh

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update submodule content"
            branch: create-pull-request/patch_submodule_content
            base: deploy-website
            commit-message: "Update submodule content"
            delete-branch: false

  # update_content:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: checkout repository
  #       uses: actions/checkout@v3

  #     - name: create pull request
  #       uses: devops-infra/action-pull-request@v0.5.5
  #       with:
  #           github_token: ${{ secrets.GITHUB_TOKEN }}
  #           title: "Update main content"
  #           source_branch: main
  #           target_branch: deploy-website
