name: Update Website
on:
  push:
    branches:
      - 'rohd-website'
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:
    


jobs:
  update_submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Create staging branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'staging'

      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd

      - name: check for changes
        run: |
            cd rohd/doc/website
            if git diff --quiet HEAD @{u}; then
                echo "No changes in submodule."
                exit 0
            fi
            cd ../../..

      - name: update src content
        run: |
          src_path="src"
          rohd_submodule_path="rohd"
          for directory in "$rohd_submodule_path/doc/website"/*; do
              directory_name=$(basename "$directory")
              echo "In "$directory_name

              if [ -d "$src_path/$directory_name" ]; then
                  echo "directory exist, removing the old directory before copy."
                  rm -r "$src_path/$directory_name"
              else
                  echo "directory not exist, proceed to copy."
              fi

              cp -r "$directory" "$src_path/$directory_name"
          done
          ls src

      - name: Commit changes and push to staging branch
        run: |
          git config --global user.email "bot@rohd.com"
          git config --global user.name "ROHD Bot"
          git status

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update Website"
            branch: final-website
            commit-message: "Update website"
            delete-branch: false

