name: update website
on:
  schedule:
    - cron: '5 8 * * 0' # Every Sunday 8.05
  workflow_dispatch:

# Top-level default, no permissions
permissions: {}

jobs:
  update_submodule:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
     
      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd
      
      - name: update src content
        run: tool/gh_actions/update_directory.sh

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update submodule content"
            branch: create-pull-request/patch_submodule_content
            base: main
            commit-message: "Update submodule content"
            delete-branch: false
