name: Update Website
on:
  push:
    branches:
      - 'rohd-website'
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:
    


jobs:
  update_submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd

      - name: check for changes
        run: |
            cd rohd/doc/website
            if git diff --quiet HEAD @{u}; then
                echo "No changes in submodule."
                exit 0
            fi
            cd ../../..

      - name: update src content
        run: tool/gh_actions/update_directory.sh

      # - name: Commit changes and push to staging branch
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     new_branch: staging

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update Website"
            # branch: staging
            base: deploy-website
            commit-message: "Update website"
            delete-branch: false

