name: update website
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '5 8 * * 0' # Evry Sunday 8.05
  workflow_dispatch:

jobs:
  update_submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: deploy-website

      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd
        
      - name: update src content
        run: tool/gh_actions/update_directory.sh

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update submodule content"
            base: deploy-website
            commit-message: "Update submodule content"
            delete-branch: true

  update_content:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update main content"
            commit-message: "Update main content"
            delete-branch: true
