name: Update Website
on:
  push:
    branches:
      - 'rohd-website'
  schedule:
    - cron: '3 * * * *'
  workflow_dispatch:
    


jobs:
  update_submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: update submodule
        run: |
            git submodule update --init --recursive
            git submodule update --remote rohd

      - name: check for changes
        run: |
            cd rohd/doc/website
            if git diff --quiet HEAD @{u}; then
                echo "No changes in submodule."
                exit 0
            fi
            cd ../../..

      - name: clean destination directory
        run: rm -rf src/*

      - name: copy files from submodule
        run: cp -R rohd/doc/website/. src/

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
            title: "Update Website"
            branch: rohd-website
            commit-message: "Update website"
            delete-branch: true

